{{ if eq .Values.useHostNetworking false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.networking.serviceLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networking.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: gameport
      port: {{ .Values.networking.gamePort | int }}
      targetPort: {{ .Values.networking.gamePort | int }}
      protocol: UDP
  {{ if .Values.networking.publishQueryPort }}
    - name: queryport
      port: {{ .Values.networking.gamePort | int | add 1 }}
      targetPort: {{ .Values.networking.gamePort | int | add 1 }}
      protocol: UDP
  {{ end }}
  type: {{ .Values.networking.serviceType }}
  selector:
    app: {{ .Release.Name }}
{{ end }}
