apiVersion: v1
kind: Service
metadata:
  name: {{ include "emby-chart.fullname" . }}
  labels:
    {{- include "emby-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.local.port }}
      targetPort: {{ .Values.service.local.portName }}
      protocol: TCP
      name: {{ .Values.service.local.portName }}
    - port: {{ .Values.service.external.port }}
      targetPort: {{ .Values.service.external.portName }}
      protocol: TCP
      name: {{ .Values.service.external.portName }}
  selector:
    {{- include "emby-chart.selectorLabels" . | nindent 4 }}
