# Stolen from: https://github.com/bitwarden/helm-charts/blob/main/.github/workflows/_build.yml
name: _build

on:
  workflow_call:
    inputs:
      chart_name:
        type: string
        required: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    name: Build Helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Helm
        uses: Azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: 'v3.13.1'

      - name: Package Helm chart
        id: helm_package
        run: |
          helm package \
            charts/${{ inputs.chart_name }}
          PKG_NAME=$(ls *.tgz)
          echo "name=$PKG_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.chart_name }}
          path: |
            ${{ steps.helm_package.outputs.name }}
            ${{ steps.helm_package.outputs.name }}.prov
          if-no-files-found: error
